# eccc-msc-amqp-alerts
# Copyright (C) 2022  Justin A. S. Bull
# See __init__.py for full notice


# From WMO-No. 386 (2015 ed), Attachment II-5 (page 80-...)
# https://library.wmo.int/doc_num.php?explnum_id=10469

# WMO standard data designators

# Data type designator T1 Matrix Table for T1T2A1A2ii definitions
import re
from datetime import datetime, timezone
from GTStoWIS2 import GTStoWIS2

country_or_territory_designators_table = {
    "AB": "Albania",
    "AG": "Argentina",
    "AH": "Afghanistan",
    "AI": "Ascension Island",
    "AJ": "Azerbaijan",
    "AK": "Alaska",
    "AL": "Algeria",
    "AN": "Angola",
    "AT": "Antigua and Barbuda, Saint Kitts and Nevis, and other British islands in the vicinity",
    "AU": "Australia",
    "AY": "Armenia",
    "AZ": "Azores",
    "BA": "Bahamas",
    "BC": "Botswana",
    "BD": "Brunei Darussalam",
    "BE": "Bermuda",
    "BH": "Belize",
    "BI": "Burundi",
    "BJ": "Benin",
    "BK": "Banks Islands",
    "BM": "Myanmar",
    "BN": "Bahrain",
    "BO": "Bolivia (Plurinational State of)",
    "BR": "Barbados",
    "BT": "Bhutan",
    "BU": "Bulgaria",
    "BV": "Bouvet Island",
    "BW": "Bangladesh",
    "BX": "Belgium, Luxembourg",
    "BY": "Belarus",
    "BZ": "Brazil",
    "CD": "Chad",
    "CE": "Central African Republic",
    "CG": "Congo",
    "CH": "Chile",
    "CI": "China",
    "CM": "Cameroon",
    "CN": "Canada",
    "CO": "Colombia",
    "CR": "Canary Islands (Spain)",
    "CS": "Costa Rica",
    "CT": "Canton Island",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    "CY": "Cyprus",
    "CZ": "Czechia",
    "DC": "Bonaire, St Eustatius and Saba",
    "DJ": "Djibouti",
    "DL": "Germany",
    "DN": "Denmark",
    "DO": "Dominica",
    "DR": "Dominican Republic",
    "EG": "Egypt",
    "EI": "Eritrea",
    "EO": "Estonia",
    "EQ": "Ecuador",
    "ER": "United Arab Emirates",
    "ES": "El Salvador",
    "ET": "Ethiopia",
    "FA": "Faroe Islands",
    "FG": "French Guiana",
    "FI": "Finland",
    "FJ": "Fiji",
    "FK": "Falkland Islands (Malvinas)",
    "FM": "Federated States of Micronesia",
    "FP": "Saint Pierre and Miquelon",
    "FR": "France",
    "FW": "Wallis and Futuna",
    "GB": "Gambia",
    "GC": "Cayman Islands",
    "GD": "Grenada",
    "GE": "Gough Island",
    "GG": "Georgia",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Greenland",
    "GM": "Guam",
    "GN": "Guinea",
    "GO": "Gabon",
    "GQ": "Equatorial Guinea",
    "GR": "Greece",
    "GU": "Guatemala",
    "GW": "Guinea­Bissau",
    "GY": "Guyana",
    "HA": "Haiti",
    "HE": "Saint Helena",
    "HK": "Hong Kong, China",
    "HO": "Honduras",
    "HU": "Hungary",
    "HV": "Burkina Faso",
    "HW": "Hawaiian Islands",
    "IC": "Comoros",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Iceland",
    "IN": "India",
    "IQ": "Iraq",
    "IR": "Islamic Republic of Iran",
    "IS": "Israel",
    "IV": "Côte d’Ivoire",
    "IY": "Italy",
    "JD": "Jordan",
    "JM": "Jamaica",
    "JP": "Japan",
    "KA": "Caroline Islands",
    "KB": "Kiribati",
    "KI": "Christmas Island",
    "KK": "Cocos Islands",
    "KN": "Kenya",
    "KO": "Republic of Korea",
    "KP": "Cambodia",
    "KR": "Democratic People’ Republic of Korea",
    "KU": "Cook Islands",
    "KW": "Kuwait",
    "KY": "Kyrgyzstan",
    "KZ": "Kazakhstan",
    "LA": "Lao People’s Democratic Republic",
    "LB": "Lebanon",
    "LC": "Saint Lucia",
    "LI": "Liberia",
    "LJ": "Slovenia",
    "LN": "Southern Line Islands",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LV": "Latvia",
    "LY": "Libya",
    "MA": "Mauritius",
    "MB": "Marion Island",
    "MC": "Morocco",
    "MD": "Madeira",
    "MF": "Saint-­Martin, Saint­-Barthélemy, Guadeloupe and other French islands in the vicinity",
    "MG": "Madagascar",
    "MH": "Marshall Islands",
    "MI": "Mali",
    "MJ": "The former Yugoslav Republic of Macedonia",
    "MK": "Montenegro",
    "ML": "Malta",
    "MN": "St Maarten",
    "MO": "Mongolia",
    "MR": "Martinique",
    "MS": "Malaysia",
    "MT": "Mauritania",
    "MU": "Macao, China",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Mariana Islands",
    "MZ": "Mozambique",
    "NC": "New Caledonia",
    "NE": "Niue",
    "NG": "Papua New Guinea",
    "NI": "Nigeria",
    "NK": "Nicaragua",
    "NL": "Netherlands",
    "NM": "Namibia",
    "NO": "Norway",
    "NP": "Nepal",
    "NR": "Niger",
    "NU": "Curaçao and Aruba",
    "NV": "Vanuatu",
    "NW": "Nauru",
    "NZ": "New Zealand",
    "OM": "Oman",
    "OO": "Monaco ",
    "OR": "South Orkney Islands",
    "OS": "Austria",
    "PF": "French Polynesia",
    "PH": "Philippines",
    "PI": "Phoenix Islands",
    "PK": "Pakistan",
    "PL": "Poland",
    "PM": "Panama",
    "PO": "Portugal",
    "PP": "Palau",
    "PR": "Peru",
    "PT": "Pitcairn",
    "PU": "Puerto Rico",
    "PY": "Paraguay",
    "QB": "Bosnia and Herzegovina",
    "QT": "Qatar",
    "RA": "Russian Federation (East)",
    "RE": "Réunion and associated islands",
    "RH": "Croatia",
    "RM": "Republic of Moldova",
    "RO": "Romania",
    "RS": "Russian Federation (West)",
    "RW": "Rwanda",
    "SB": "Sri Lanka",
    "SC": "Seychelles",
    "SD": "Saudi Arabia",
    "SG": "Senegal",
    "SI": "Somalia",
    "SK": "Sarawak",
    "SL": "Sierra Leone",
    "SM": "Suriname",
    "SN": "Sweden",
    "SO": "Solomon Islands",
    "SP": "Spain",
    "SQ": "Slovakia",
    "SR": "Singapore",
    "SU": "Sudan",
    "SV": "Swaziland",
    "SW": "Switzerland",
    "SX": "Santa Cruz Islands",
    "SY": "Syrian Arab Republic",
    "SZ": "Spitzbergen Islands",
    "TA": "Tajikistan",
    "TC": "Tristan da Cunha",
    "TD": "Trinidad and Tobago",
    "TG": "Togo",
    "TH": "Thailand",
    "TI": "Turks and Caicos Islands",
    "TK": "Tokelau",
    "TM": "Timor­Leste",
    "TN": "United Republic of Tanzania",
    "TO": "Tonga",
    "TP": "Sao Tome and Principe",
    "TR": "Turkmenistan",
    "TS": "Tunisia",
    "TU": "Turkey",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UK": "United Kingdom of Great Britain and Northern Ireland",
    "UR": "Ukraine",
    "US": "United States of America",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VG": "Saint Vincent and the Grenadines",
    "VI": "Virgin Islands",
    "VN": "Venezuela (Bolivarian Republic of)",
    "VS": "Viet Nam",
    "YE": "Yemen",
    "YG": "Serbia",
    "ZA": "South Africa",
    "ZB": "Zambia",
    "ZM": "Samoa",
    "ZR": "Democratic Republic of the Congo",
    "ZS": "South Sudan",
    "ZW": "Zimbabwe",
}

area_designators_table = {
    "AA": "Antarctic",
    "AC": "Arctic",
    "AE": "South­East Asia",
    "AF": "Africa",
    "AM": "Central Africa",
    "AO": "West Africa",
    "AP": "Southern Africa",
    "AS": "Asia",
    "AW": "Near East",
    "AX": "Arabian Sea area",
    "BQ": "Baltic Sea area",
    "CA": "Caribbean and Central America",
    "EA": "East Africa",
    "EC": "East China Sea area",
    "EE": "Eastern Europe",
    "EM": "Middle Europe",
    "EN": "Northern Europe",
    "EU": "Europe",
    "EW": "Western Europe",
    "FE": "Far East",
    "GA": "Gulf of Alaska area",
    "GX": "Gulf of Mexico area",
    "IO": "Indian Ocean area",
    "ME": "Eastern Mediterranean area",
    "MM": "Mediterranean area",
    "MP": "Central Mediterranean area",
    "MQ": "Western Mediterranean area",
    "NA": "North America",
    "NT": "North Atlantic area",
    "OC": "Oceania",
    "OH": "Sea of Okhotsk",
    "PA": "Pacific area",
    "PE": "Persian Gulf area",
    "PN": "North Pacific area",
    "PQ": "Western North Pacific",
    "PS": "South Pacific area",
    "PW": "Western Pacific area",
    "PZ": "Eastern Pacific area",
    "SA": "South America",
    "SE": "Southern Ocean area",
    "SJ": "Sea of Japan area",
    "SS": "South China Sea area",
    "ST": "South Atlantic area",
    "XE": "Eastern hemisphere",
    "XN": "Northern hemisphere",
    "XS": "Southern hemisphere",
    "XT": "Tropical belt",
    "XW": "Western hemisphere",
    "XX": "No appropriate area",
}

pattern = re.compile(
    r"^(?P<data_type_1>[A-Z])(?P<data_type_2>[A-Z])(?P<country_or_area>[A-Z][A-Z])([0-9][0-9]) (?P<centre>[A-Z]{4}) (?P<datetime>[0-9]{6})$"
)

gts_tables = GTStoWIS2()
gts_tables.genTableTTAAii()


def decode_header(wmo_gts_comms_header: str):
    result = pattern.match(wmo_gts_comms_header)
    if result is None:
        raise ValueError("Invalid header. Must be format of 'T₁T₂A₁A₂ii CCCC YYGGgg'")
    parsed_header = result.groupdict()
    current_utc_time = datetime.utcnow()

    data_type_1_tbl = gts_tables.tableTTAAii.get(parsed_header["data_type_1"], {})

    area = country_or_territory_designators_table.get(
        parsed_header["country_or_area"]
    ) or area_designators_table.get(parsed_header["country_or_area"])

    cccc_entry = gts_tables.tableCCCC.get(parsed_header["centre"])
    # Not all centres are named. The lookup table is a bit dirty, there are a few ways
    # it indicates there's no name
    if cccc_entry is None:
        best_centre_name = parsed_header["centre"]
    else:
        best_centre_name = cccc_entry.get("name")
        if (
            best_centre_name is None
            or best_centre_name == "--"
            or best_centre_name == "MISSING"
        ):
            best_centre_name = cccc_entry["centre"]

    return {
        "data_type": data_type_1_tbl.get("topic"),
        "data_type_sub": data_type_1_tbl["T2"].get(parsed_header["data_type_2"]),
        "area": area,
        "centre": best_centre_name,
        "datetime": datetime(
            current_utc_time.year,
            current_utc_time.month,
            int(parsed_header["datetime"][0:2]),
            int(parsed_header["datetime"][2:4]),
            int(parsed_header["datetime"][4:6]),
            tzinfo=timezone.utc,
        ),
    }


def pretty_header(wmo_gts_comms_header: str):
    _str = ""
    header_info = decode_header(wmo_gts_comms_header)
    for k, v in header_info.items():
        _str += "{:<15} {}\n".format(k, v)
    return _str
